### ISSUE TITLE
Email contact people to distribute news about python and neuromatch academy

### ISSUE THREAD

**Issue by GHarmata** [brainhack-uiowa/2020-brainhack#11]
- [x] Psychology (psy-dept@list.uiowa.edu through becky-huber@uiowa.edu)
- [x] IIBI (hans-johnson@uiowa.edu)
- [x] INI (meghan-lawler@uiowa.edu)
- [x] Psychiatry (jatin-vaidya@uiowa.edu)
- [x] Computational Psychiatry (jacob-michaelson@uiowa.edu)
- [x] Neuroscience (megan-meyer@uiowa.edu)
- [x] Informatics (juanpablo-hourcade@uiowa.edu)
- [x] Graduate Women in Science (kelle-nett@uiowa.edu)
- [x] Biomedical Engineering (bme@engineering.uiowa.edu)
- [x] Computer Science (sriram-pemmaraju@uiowa.edu)
- [x] Electrical Engineering (ece@engineering.uiowa.edu)
- [x] Biomedical Sciences (jodi-graff@uiowa.edu)

**Comment by GHarmata** [comment]
Emailed Meghan Lawler for INI.

**Comment by GHarmata** [comment]
Emailed Megan Meyer for Neuroscience Program.

**Comment by GHarmata** [comment]
Emailed Becky Huber for Psychology

**Comment by GHarmata** [comment]
Emailed Hans for IIBI

**Comment by GHarmata** [comment]
Emailed Jatin Vaidya for Psychiatry

**Comment by GHarmata** [comment]
Emailed Jodi Graff for Biomedical Science

**Comment by GHarmata** [comment]
Emailed Jake Michaelson for Computational Psychiatry; also mentioned idea of TAs and mentors for neuromatch academy

**Comment by jdkent** [comment]
Awesome work Gail!
Can @mpipoly, @tientong98 , or @taylor-r-thomas help round off the rest of the contact list?

**Comment by mpipoly** [comment]
I eemailed juan pablo hourcade

**Comment by mpipoly** [comment]
I emailed kelle nette for GWIS

**Comment by mpipoly** [comment]
I emailed BME

**Comment by mpipoly** [comment]
I emailed computer science

**Comment by mpipoly** [comment]
I emailed electrical engineering

**Comment by jdkent** [comment]
Awesome, thank you @mpipoly, that rounds off the list!
