### ISSUE TITLE
Registration survey

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2020-brainhack#12]
We will still want to track who comes to hacky hour for the uibrainhack so we get an idea of their python/programming knowledge experience and what they hope to gain. (and afterwords we can ask if we really prepared them for neuromatch)

**Comment by jdkent** [comment]
Here is the software carpentry pre-workshop survey, we should use this: https://carpentries.github.io/assessment-archives/pre-workshop/pre-workshop.html

**Comment by jdkent** [comment]
and here is last year's qualtrics survey: https://uiowa.ca1.qualtrics.com/jfe/preview/SV_3JlvEwdpnyEE8GV?Q_SurveyVersionID=current&Q_CHL=preview

**Comment by jdkent** [comment]
and you can log into uiowa qualtrics to make a survey: https://its.uiowa.edu/qualtrics

**Comment by mpipoly** [comment]
I believe that all of the google colab sw carpentry tutorials have been copied over? I just did 9,10,11 @jdkent

**Comment by GHarmata** [comment]
I think we should keep it simple and not use the software carpentry survey for tracking attendance.  Just obtain email and purpose for being at hacky hour each time.  Then we can follow up with a more detailed survey after all the sessions are over.

**Comment by mpipoly** [comment]
Ok, I have a 3 question Qualtrics survey set-up already. if it is not useful, no worries. let me know what you think 9dding u as collaborators now)

**Comment by jdkent** [comment]
I cannot find the neurohackademy question, but [the Programming languages software carpentry question would be a good substitute](https://carpentries.github.io/assessment-archives/pre-workshop/pre-workshop.html#programming-languages-r-python-etc), 

And my opinion is to keep the wording so it's programming language agnostic, it will be nice to know if people coming have any programming experience whatsoever since the lessons we are covering are just as much (if not more) about programming fundamentals as they are about python.

**Comment by jdkent** [comment]
[I've updated the registration survey](https://uiowa.ca1.qualtrics.com/jfe/preview/SV_6ERTvtqEXnbSVcV?Q_SurveyVersionID=current&Q_CHL=preview) (minor edits and added the carpentry question, I changed my mind about keeping the question programming language agnostic)

**Comment by jdkent** [comment]
I'm going to release this version of the survey so Jake Michaelson can share it with computational psychiatry, but please feel free to give feedback and we can modify it as necessary.

**Comment by mpipoly** [comment]
@jdkent That looks great. I was wondering if we could use the "program" question as leverage if we ever decided to request something but maybe departmental is good enough.

**Comment by jdkent** [comment]
My sense is that departments are often the entities with funding/infrastructure,with neuroscience/genetics being the two notable exceptions.

My thought was that most people see their department/program as the same entity and may not know how to respond/some people (that have contacted me) do not belong to any program, but are affiliated with a department.

But I do not hold a strong opinion if you want to add it back in.

**Comment by mpipoly** [comment]
Yes, so it would be (if applicable) but i agree it is likely that departments will be our funders so we should avoid for now. Any no department folks can indicate "carver college of medicine" or "graduate college."

**Comment by jdkent** [comment]
we will considered this solved for now.
