### ISSUE TITLE
transcribe software carpentry lessons to google colab notebooks

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2020-brainhack#13]
ref swcarpentry/python-novice-inflammation#819

For participants to use the same technology as they will be using at neuromatch.

**Comment by jdkent** [comment]
I have a repository set up called [python-novice-inflammation-colab](https://github.com/brainhack-uiowa/python-novice-inflammation-colab),

which you can access as a [google colab](https://colab.research.google.com/github/brainhack-uiowa/python-novice-inflammation-colab)

From the google colab interface you can select a notebook and start editing it and save it either on your google drive or download it, if you're comfortable with git you should be able to edit the repository directly, otherwise you can email/link the python notebook to me and I will get it added to the colab repo.

@tientong98 @mpipoly @taylor-r-thomas @GHarmata Pick two/three lessons in [the issues tab](https://github.com/brainhack-uiowa/python-novice-inflammation-colab/issues) and transcribe the software carpentry lesson to the notebook.

It would be awesome to get a first pass done by the end of next week!

**Comment by jdkent** [comment]
[README has an example video on transcribing an episode of the python lesson](https://github.com/brainhack-uiowa/python-novice-inflammation-colab/blob/master/README.md)

**Comment by mpipoly** [comment]
I believe that all of the google colab sw carpentry tutorials have been copied over? I just did 9,10,11 @jdkent

**Comment by jdkent** [comment]
Thanks @mpipoly, looks like they are all covered!
