### ISSUE TITLE
Create slack group

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2020-brainhack#15]
Virtual communication will be more important than ever this year, we used slack in the past and I think it will work well this year too.

- [create a slack group](https://slack.com/get-started#/)

**Comment by jdkent** [comment]
- name of slack group: 2020-uibrainhack
- create introductions channel for everyone to introduce themselves (position/background, what they hope to gain from participating)
- create questions channel for asking questions about the tutorials
- create resources channel for everyone to share helpful resources for learning python

**Comment by tien-tong** [comment]
@jdkent  The slack group has been created. Can I get an email list to send invitations to people?

**Comment by jdkent** [comment]
can you make a generic invitation? I'll put that link on the website.

**Comment by tien-tong** [comment]
Invite link

https://join.slack.com/t/2020-uibrainhack/shared_invite/zt-eaicf06b-FomGguXg5fZjqyFT7iDGhg

(expires in 30 days)

**Comment by jdkent** [comment]
Thanks!
