### ISSUE TITLE
Flyer with link

### ISSUE THREAD

**Issue by mpipoly** [brainhack-uiowa/2020-brainhack#20]
-Create a qualtrics survey to ask about attendance (yes,no,maybe) and their contact information.

-Name
-Department
-program (if applicable)
-email

**Comment by jdkent** [comment]
Thanks for opening this, for this year, is this being replaced with #12?

**Comment by mpipoly** [comment]
I thought the way 12 was about tracking daily attendance at Hacky hour related to Brainhack activities versus non-brainhack activities? @jdkent

**Comment by jdkent** [comment]
follow up: #12 will serve as registration for the python tutorials, and #23 will take care of how we track participation.
