### ISSUE TITLE
Create Zoom Poll

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2020-brainhack#22]
@kerry-tarrant: create a zoom poll to be asked at the end of each session where we post the question:

How is the pacing of the tutorials?
a) too slow
b) just right
c) too fast

**Comment by kerry-tarrant** [comment]
[Meeting reports for Zoom polls.pdf](https://github.com/brainhack-uiowa/2020-brainhack/files/4626052/Meeting.reports.for.Zoom.polls.pdf)

**Comment by jdkent** [comment]
Thanks! If you still do not have access to the hacky hour zoom meeting, I just created a poll we can test this Friday at Hacky Hour to see if it works.

**Comment by kerry-tarrant** [comment]
@jdkent Sounds good! Essentially, as host or owner, it's as easy as generating a poll. I just tested it, and it worked out fine. It looks like you generate poll results for specific day(s), which will be super helpful.

**Comment by jdkent** [comment]
Poll created and tested.
