### ISSUE TITLE
legitimize ourselves as a group

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2020-brainhack#31]
what do we need to do to be an official group?

**Comment by taylor-r-thomas** [comment]
I talked to Megan and Jodi, and they said we need to do this: https://leadandserve.uiowa.edu/student-organizations/how-to-start-a-student-organization/ But the deadline for this year was January. I'm also talking to Jodi about how we could possibly received additional financial support from the College of Medicine. I will post updates.

**Comment by jdkent** [comment]
Thanks Taylor!

**Comment by mpipoly** [comment]
Hi @taylor-r-thomas , any updates with this? Otherwise, should we close it out for now @jdkent ?

**Comment by taylor-r-thomas** [comment]
I'll forward @mpipoly and @jdkent the email correspondence I had with Jodi Graff. Short answer is the deadline to become a student org was in January, so we'll have to wait til then. Additional money or funding isn't directly available through CCOM but may be administered on a case-by-case basis (which I assume means we'd have to apply each time)

**Comment by mpipoly** [comment]
Hi @taylor-r-thomas ! Thank you again for looking into this. I wasn't sure if anything had changed on that front. :)

**Comment by jdkent** [comment]
Thanks! I will close this issue.
