### ISSUE TITLE
week 2 intro topics

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2020-brainhack#37]
- [x] introduce any brainhack members/python experts in attendance that were not in attendance last week.
- [x] demo how to edit and save google colab notebooks
  - demo how to expand all cells `ctrl+[`
- [x] deploy survey to get idea of how we are doing with the pace of tutorials.
- [x] go over main points of [analyzing patient data](https://swcarpentry.github.io/python-novice-inflammation/02-numpy/index.html)
- [x] give another ice breaker? (something you learned this week (could be related or unrelated to python)
- [x] split out into discussion groups

**Comment by mpipoly** [comment]
I think we successfully did this :). I have a small introduction in my group :)
