### ISSUE TITLE
Create post-survey

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2020-brainhack#43]
We want to identify what was done well and what should be improved for next year's tutorials.
[Here is last year's post survey questions](https://github.com/brainhack-uiowa/2019-brainhack/files/3521495/Default.Report.pdf) to use as inspiration (some questions are not relevant)

**Comment by jdkent** [comment]
@mpipoly, you made the registration survey, so you would have the most experience creating a qualtrics survey (AFAIK), but if anyone else could work on this, that would ensure Marco is not the only one that knows how to make the survey, 

[Introduction to the material is here](https://basecamp.qualtrics.com/series/learn-to-use-qualtrics-research-core), you need to log in using the uiowa domain login
(or you can fumble around as I did to learn what I needed)

**Comment by kerry-tarrant** [comment]
Here's a quick link uiowa.qualtrics.com

**Comment by jdkent** [comment]
thanks @kerry-tarrant!, if you click on tools then collaborate, you can add us to have access to the survey.
![Screenshot from 2020-07-05 22-56-18](https://user-images.githubusercontent.com/12564882/86554293-d578c600-bf12-11ea-9a8e-c92d36b6cbfe.png)

![Screenshot from 2020-07-05 22-57-34](https://user-images.githubusercontent.com/12564882/86554370-0658fb00-bf13-11ea-9cb2-dc279e274b68.png)

**Comment by mpipoly** [comment]
Hi all, @kerry-tarrant did you initiate a new survey?

**Comment by mpipoly** [comment]
It is fine if not, I can quickly create one and folks can review and edit it :)

**Comment by kerry-tarrant** [comment]
I have not. That would be really nice!

**Comment by jdkent** [comment]
@mpipoly, if you are working on this, please copy the project so that last year's responses are not mixed in with this year's responses.

Thanks!
![Screenshot from 2020-07-07 14-32-24](https://user-images.githubusercontent.com/12564882/86833206-d74fa000-c05e-11ea-933a-090f1bcaad4a.png)

![Screenshot from 2020-07-07 14-34-27](https://user-images.githubusercontent.com/12564882/86833342-0403b780-c05f-11ea-9cdc-68e00a51c4f1.png)

**Comment by mpipoly** [comment]
@jdkent I just made a new survey in qualities which I will link for all of you to review/comment.... unless you are asking me to copy for some other reason?

**Comment by jdkent** [comment]
nope, making a new survey works just as well.

**Comment by mpipoly** [comment]
Hi all @GHarmata @jdkent @tientong98 @taylor-r-thomas @kerry-tarrant I have sent you links with the rough draft of the exit survey. I had a different format for the original from last year... i deviated from it a bit because this year we just did tutorials and never met in person. I think it could definitely use some re-wording and maybe some structural/organizational changes. I also am not sure if I am missing stuff. It is ~12 questions long... which is brief enough.... Thoughts?

**Comment by jdkent** [comment]
Thanks! I did a first pass, I would also be curious to how people felt about slack, or if they would prefer we sent all additional resources we shared through email and should only use email for communication. I love using slack (or any other irc client that is not email), but I recognize others feel differently.

**Comment by jdkent** [comment]
also, we can ask about/advertise hacky hour and if they would attend hacky hour in the future with questions.

**Comment by kerry-tarrant** [comment]
The survey sounds really good! I just have a few comments about some of the questions. I think question 5 is a little ambiguous. Are we talking about the whole event or each lesson? For question 6, I'm not sure how to use the hint.

I added Q13 to ask participants about their experience with Slack. I also added a couple sentences advertising Hacky Hour after the termination of the survey.

**Comment by jdkent** [comment]
great work, kerry, I like the end message! I've separated some questions to be about either the tutorial material (notebooks/readings) or the Friday discussions.

Made question 5 about the whole event.

**Comment by jdkent** [comment]
I think I'm good with the post survey, does anyone else have any comments/suggestions?

**Comment by mpipoly** [comment]
@jdkent Do we have a rough estimate of the time it takes to complete it? I personally am more swayed to complete a survey that says "5 minutes" compared to not knowing how long :)

**Comment by jdkent** [comment]
The estimate on the website (~3 minutes) was actually pretty good for me, and I filled out every write-in answer.
If someone was really being thorough, it could take up to 5 minutes.

**Comment by mpipoly** [comment]
We should sell it as a 3-minute survey. I want to encourage how fast and easy it is to complete this.

**Comment by jdkent** [comment]
that sounds good to me, I can send the emails out today.

**Comment by jdkent** [comment]
[survey results](https://github.com/brainhack-uiowa/2020-brainhack/files/4962202/Default.Report.pdf)
