### ISSUE TITLE
track what advertisements are working

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2020-brainhack#5]
we can use the url to embed information on the survey to see what method of distribution is most successful (e.g., posters, emails, facebook, twitter, etc.): https://www.qualtrics.com/support/survey-platform/distributions-module/social-media-distribution/

**Comment by mpipoly** [comment]
Ooooo this is great thinkins

**Comment by jdkent** [comment]
done & done, now we wait and see what links people use to register.
