### ISSUE TITLE
Main contact person/people for questions?

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2020-brainhack#8]
We need a main contact person to direct people to for questions.

**Comment by mpipoly** [comment]
Is this a liason for before, during, and after workshops or?

**Comment by jdkent** [comment]
This is the person with their email address [on the website](https://brainhack-uiowa.github.io/uibrainhack). So this would be someone who catches questions from people visiting the website.

**Comment by mpipoly** [comment]
If no one else can do it. I am fine having my information posted.

**Comment by jdkent** [comment]
Thanks @mpipoly! I'll put your email on the website.
