### ISSUE TITLE
Email ISRC/HPC for help

### ISSUE THREAD

**Issue by jdkent** [brainhack-uiowa/2020-brainhack#9]
I sent out an email ISRC and HPC for help, here is the template:

Hi!

I'm a graduate student in the Neuroscience Program and a member of the University of Iowa's Brainhack Committee. Marco and Kerry (cc'd) are also members of the committee.

Due to in-person events/conferences being cancelled, a movement in the neuroscience community has produced an online academy called neuromatch (July 13-31). Neuromatch academy will be a great opportunity for anyone interested in the brain to learn more about data analysis, however, they have some course prerequisites:

All students need to have basic coding proficiency in Python, foundational neuroscience knowledge, and some foundational mathematical concepts such as linear algebra, calculus, and basic probability theory. If you do not have these skills or knowledge before the course, there are *lots* of options for catching up before you begin!  The Neuromatch Academy website will be posting recommended resources to help you get the background you need to succeed and get the most out of the course.

We want to help anyone that wants to participate to gain the foundational skills necessary to get the most out of neuromatch academy.

Currently, we are scheduling to release tutorial content on Monday of each week starting May 18th and have discussion/questions answered every Friday for a total of 8 tutorials. (see schedule).

We are planning on hosting the Friday discussions (3:00pm-5:00pm) via zoom during an event called hacky hour.

ASKING FOR HELP
Would you be willing to work with us to help people learn fundemental concepts about python/linear algebra/calculus/probability theory?

This help could take the form of:
attending hacky hour to help field questions about the tutorial materials
suggesting/curating tutorial materials we should use to help people learn these concepts
hosting a tutorial about one of the above concepts (could be during hacky hour or another time)

Let us know if anyone in HPC would be interested in helping out this summer.

Thank you for your time!
James

**Comment by jdkent** [comment]
The real email has links, I'll put those in...

**Comment by jdkent** [comment]
Rambling email reply to help clarify what the ISRC can do to help:

Hi Fred,

Thanks for offering to forward this to your media folks, let me know if you need an image or additional information.

I agree, neural data does sound like it would look a lot different than survey data, but I believe ISRC members have valuable knowledge that translates to neuroscience (and many fields). The knowledge falls under two domains: Data Management and Data Analysis.

For example, here is a (non-exhaustive) list of what I've noticed ISRC could offer hacky hour and help neuroscience graduate students prepare for a summer course.
How to check for missing values (strategies for cleaning data)
wide versus long format
how do I change my reference group in a factor (R)?
how do I graph my dependent measure by different groups?
How do I write readable code?
How do I check my assumptions for linear regression?
How do I install R/python?
How do I write a function? (python/R fundementals)
How do I share my code on github?
How do I use git?
Beyond data management and some statistics, I think neuroscience has a lot to learn from survey data collection methods.
(Excuse my ignorance for the following sentence).
If we view collecting survey data as sampling various locations at various timepoints (panel data); neuroscience collects data in a very similar manner using brain measures from multiple people over the course of minutes/months (depending on what is being measured and at what frequency)

Additionally, network analysis is becoming very popular in neuroscience, and network analysis has a strong foundation in political science/economics, so even sharing the concepts of networks would lead to beneficial interactions.

I'm brushing over a lot of nuance, but my main point is I believe ISRC members have knowledge that could lead to beneficial conversations during Hacky Hour that are not directly related to the types of data we collect (but I also believe there are similarities in our data as well).

Those conversations will help people from neuroscience have the prerequisite knowledge for a summer course (neuromatch), but if ISRC members would like to continue attending Hacky Hour, it is a weekly meetup that strives to cross disciplinary boundaries, and I would love to see more representation if people are interested.

Hacky Hour generally is like a cross between office hours/hangout for people that are working on solving problems with data and code, so it can be a nice place to get new ideas and strengthen your own understanding by explaining concepts to someone outside your discipline. I have a list of reasons to attend hacky hour if you're still curious.

If anyone would like to zoom in, the meeting ID for Hacky Hour is: 412-096-940 (Fridays anytime between 3:00pm-5:00pm)

Sorry about the long ramble, but I hope this helps clear up how the ISRC can help.

Best,
James

**Comment by mpipoly** [comment]
Hi James, This is great!

**Comment by jdkent** [comment]
ISRC will require monetary compensation for helping, however, the HPC folks appear to be able expend some bandwidth by acting as "ask the experts" during hacky hour, will follow up after meeting with HPC folks.

**Comment by jdkent** [comment]
closing since we've had the follow up conversations.
